### ISSUE TITLE
openai key was inserted but getting error

### ISSUE THREAD

**Issue by SayaAEP** [zeeoneofficial/Haruka-Md#8]
.ai / .aidraw / .chadgpt

![image](https://github.com/zeeoneofficial/Haruka-Md/assets/91467886/744bbfcc-cc72-43fb-8b28-1fc103ec3f86)
![image](https://github.com/zeeoneofficial/Haruka-Md/assets/91467886/0445c2cf-30cd-49e2-b08e-79d3f606fff5)

![image](https://github.com/zeeoneofficial/Haruka-Md/assets/91467886/3066a96a-2d2b-44ae-9033-93959ddcfc38)
![image](https://github.com/zeeoneofficial/Haruka-Md/assets/91467886/d01b86bc-2eb5-4c4b-abe8-4bdcf2fbb800)
but heck yeah. i'm insert the openaikey correctly

**Comment by 0zunu** [comment]
up

**Comment by rayqlf** [comment]
up too

**Comment by sayaaep** [comment]
up

**Comment by sayaaep** [comment]
abandoned project idk why
